import 'package:intl/intl.dart';

/// Receipt Data Model
/// 
/// This class represents a single receipt/expense in the TrustExpense app.
/// It follows the repository pattern and maps directly to the 'receipts' table
/// in Supabase (PostgreSQL database).
/// 
/// Data Flow:
/// 1. User captures receipt photo
/// 2. OCR extracts text from image
/// 3. AI classifies the expense category
/// 4. Receipt object is created with all data
/// 5. Saved to Supabase database
/// 6. Displayed in UI (History, Summary screens)
/// 
/// Database Schema (Supabase):
/// - id: UUID (primary key, auto-generated)
/// - user_id: UUID (foreign key to auth.users)
/// - amount: DECIMAL (expense amount)
/// - date: TIMESTAMP (receipt date)
/// - merchant: TEXT (store/vendor name)
/// - category: TEXT (AI-predicted category)
/// - category_confidence: DECIMAL (AI confidence score 0.0-1.0)
/// - manual_override: BOOLEAN (true if user manually changed category)
/// - image_url: TEXT (Supabase Storage URL for receipt image)
/// - ocr_text: TEXT (full OCR-extracted text)
/// - created_at: TIMESTAMP (auto-generated)
/// - updated_at: TIMESTAMP (auto-updated)
class Receipt {
  // Unique identifier (UUID) - generated by Supabase
  final String id;
  
  // User who owns this receipt (UUID from Supabase Auth)
  final String userId;
  
  // Total amount spent on this receipt
  final double amount;
  
  // Date of the transaction (from receipt or user input)
  final DateTime date;
  
  // Name of the store/merchant (extracted from OCR or user input)
  final String merchant;
  
  // Expense category (predicted by AI or set by user)
  // Examples: "Food & Dining", "Transportation", "Shopping", etc.
  final String category;
  
  // Confidence score from AI classification (0.0 to 1.0)
  // Higher values mean the AI is more confident about the category
  final double categoryConfidence;
  
  // Flag indicating if user manually changed the AI-predicted category
  // true = user override, false = AI prediction accepted
  final bool manualOverride;
  
  // URL to the receipt image stored in Supabase Storage
  // Null if image upload failed or was skipped
  final String? imageUrl;
  
  // Full text extracted from receipt via OCR
  // Used for searching and re-classification
  final String? ocrText;
  
  // Timestamp when this receipt was first created
  final DateTime createdAt;
  
  // Timestamp when this receipt was last modified
  final DateTime updatedAt;
  
  // ============================================================================
  // BLOCKCHAIN CERTIFICATION FIELDS
  // ============================================================================
  
  // SHA-256 hash of receipt data for blockchain certification
  final String? certificateHash;
  
  // Blockchain transaction hash (Sepolia testnet)
  final String? blockchainTxHash;
  
  // Certificate ID from smart contract
  final String? certificateId;
  
  // Timestamp when receipt was certified on blockchain
  final DateTime? certifiedAt;
  
  // Certification status: pending, submitted, confirmed, failed
  final String? certificationStatus;
  
  // Block number where certificate was mined
  final int? blockNumber;
  
  // Wallet address that certified this receipt
  final String? certifierAddress;

  /// Constructor - creates a Receipt instance
  /// 
  /// All fields except optional ones (imageUrl, ocrText) are required.
  /// In practice, receipts are usually created via fromJson() when loading
  /// from the database, or via the repository when creating new receipts.
  const Receipt({
    required this.id,
    required this.userId,
    required this.amount,
    required this.date,
    required this.merchant,
    required this.category,
    this.categoryConfidence = 0.0,
    this.manualOverride = false,
    this.imageUrl,
    this.ocrText,
    required this.createdAt,
    required this.updatedAt,
    // Blockchain fields
    this.certificateHash,
    this.blockchainTxHash,
    this.certificateId,
    this.certifiedAt,
    this.certificationStatus,
    this.blockNumber,
    this.certifierAddress,
  });

  /// Deserialize from JSON (Supabase → Dart object)
  /// 
  /// This factory constructor converts JSON data from Supabase into a Receipt object.
  /// Supabase returns data in snake_case (e.g., 'user_id'), which we convert to
  /// camelCase Dart properties (e.g., userId).
  /// 
  /// Used when:
  /// - Fetching receipts from database
  /// - Loading receipt history
  /// - Receiving real-time updates
  factory Receipt.fromJson(Map<String, dynamic> json) {
    return Receipt(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      amount: (json['amount'] as num).toDouble(),
      date: DateTime.parse(json['date'] as String),
      merchant: json['merchant'] as String,
      category: json['category'] as String,
      categoryConfidence: (json['category_confidence'] as num?)?.toDouble() ?? 0.0,
      manualOverride: json['manual_override'] as bool? ?? false,
      imageUrl: json['image_url'] as String?,
      ocrText: json['ocr_text'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
      // Blockchain fields
      certificateHash: json['certificate_hash'] as String?,
      blockchainTxHash: json['blockchain_tx_hash'] as String?,
      certificateId: json['certificate_id'] as String?,
      certifiedAt: json['certified_at'] != null 
        ? DateTime.parse(json['certified_at'] as String) 
        : null,
      certificationStatus: json['certification_status'] as String?,
      blockNumber: json['block_number'] as int?,
      certifierAddress: json['certifier_address'] as String?,
    );
  }

  /// Serialize to JSON (Dart object → Supabase)
  /// 
  /// Converts this Receipt object to JSON format for Supabase.
  /// Includes all fields including id, createdAt, and updatedAt.
  /// 
  /// Used for:
  /// - Full object serialization
  /// - Caching
  /// - Debugging
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'amount': amount,
      'date': date.toIso8601String(),
      'merchant': merchant,
      'category': category,
      'category_confidence': categoryConfidence,
      'manual_override': manualOverride,
      'image_url': imageUrl,
      'ocr_text': ocrText,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
      // Blockchain fields
      'certificate_hash': certificateHash,
      'blockchain_tx_hash': blockchainTxHash,
      'certificate_id': certificateId,
      'certified_at': certifiedAt?.toIso8601String(),
      'certification_status': certificationStatus,
      'block_number': blockNumber,
      'certifier_address': certifierAddress,
    };
  }

  /// Serialize for INSERT operation (creating new receipt)
  /// 
  /// This excludes fields that Supabase auto-generates:
  /// - id: Auto-generated UUID
  /// - created_at: Auto-set to current timestamp
  /// - updated_at: Auto-set to current timestamp
  /// 
  /// Used when:
  /// - Saving a new receipt to database
  /// - Creating receipt after OCR processing
  Map<String, dynamic> toInsertJson() {
    return {
      'user_id': userId,
      'amount': amount,
      'date': date.toIso8601String(),
      'merchant': merchant,
      'category': category,
      'category_confidence': categoryConfidence,
      'manual_override': manualOverride,
      'image_url': imageUrl,
      'ocr_text': ocrText,
      // Blockchain fields (for new receipts)
      'certificate_hash': certificateHash,
      'certification_status': certificationStatus,
    };
  }

  /// Serialize for UPDATE operation (modifying existing receipt)
  /// 
  /// This excludes immutable fields:
  /// - id: Cannot be changed
  /// - user_id: Cannot be changed
  /// - created_at: Cannot be changed
  /// 
  /// Updates the updated_at timestamp to current time.
  /// 
  /// Used when:
  /// - User edits receipt details
  /// - User changes category (manual override)
  /// - Updating receipt information
  Map<String, dynamic> toUpdateJson() {
    return {
      'amount': amount,
      'date': date.toIso8601String(),
      'merchant': merchant,
      'category': category,
      'category_confidence': categoryConfidence,
      'manual_override': manualOverride,
      'image_url': imageUrl,
      'ocr_text': ocrText,
      'updated_at': DateTime.now().toIso8601String(),
      // Blockchain fields (can be updated)
      'certificate_hash': certificateHash,
      'blockchain_tx_hash': blockchainTxHash,
      'certificate_id': certificateId,
      'certified_at': certifiedAt?.toIso8601String(),
      'certification_status': certificationStatus,
      'block_number': blockNumber,
      'certifier_address': certifierAddress,
    };
  }

  /// Create a modified copy of this receipt
  /// 
  /// This is the immutable update pattern in Dart. Instead of modifying
  /// the existing object, we create a new one with updated values.
  /// 
  /// Example usage:
  /// ```dart
  /// final updatedReceipt = receipt.copyWith(
  ///   category: 'Food & Dining',
  ///   manualOverride: true,
  /// );
  /// ```
  /// 
  /// Used when:
  /// - User edits receipt in UI
  /// - Updating state in Provider
  /// - Creating modified versions for testing
  Receipt copyWith({
    String? id,
    String? userId,
    double? amount,
    DateTime? date,
    String? merchant,
    String? category,
    double? categoryConfidence,
    bool? manualOverride,
    String? imageUrl,
    String? ocrText,
    DateTime? createdAt,
    DateTime? updatedAt,
    // Blockchain fields
    String? certificateHash,
    String? blockchainTxHash,
    String? certificateId,
    DateTime? certifiedAt,
    String? certificationStatus,
    int? blockNumber,
    String? certifierAddress,
  }) {
    return Receipt(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      amount: amount ?? this.amount,
      date: date ?? this.date,
      merchant: merchant ?? this.merchant,
      category: category ?? this.category,
      categoryConfidence: categoryConfidence ?? this.categoryConfidence,
      manualOverride: manualOverride ?? this.manualOverride,
      imageUrl: imageUrl ?? this.imageUrl,
      ocrText: ocrText ?? this.ocrText,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      // Blockchain fields
      certificateHash: certificateHash ?? this.certificateHash,
      blockchainTxHash: blockchainTxHash ?? this.blockchainTxHash,
      certificateId: certificateId ?? this.certificateId,
      certifiedAt: certifiedAt ?? this.certifiedAt,
      certificationStatus: certificationStatus ?? this.certificationStatus,
      blockNumber: blockNumber ?? this.blockNumber,
      certifierAddress: certifierAddress ?? this.certifierAddress,
    );
  }

  /// Get formatted amount with currency symbol
  /// 
  /// Example: 45.99 → "$45.99"
  String get formattedAmount => '\$${amount.toStringAsFixed(2)}';

  /// Get formatted date in readable format
  /// 
  /// Example: DateTime(2024, 1, 15) → "Jan 15, 2024"
  String get formattedDate => DateFormat('MMM dd, yyyy').format(date);

  /// Get short formatted date
  /// 
  /// Example: DateTime(2024, 1, 15) → "01/15/24"
  String get shortFormattedDate => DateFormat('MM/dd/yy').format(date);

  /// String representation for debugging
  @override
  String toString() {
    return 'Receipt(id: $id, merchant: $merchant, amount: $formattedAmount, date: $formattedDate, category: $category)';
  }

  /// Equality comparison based on ID
  /// 
  /// Two receipts are equal if they have the same ID (UUID)
  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is Receipt && other.id == id;
  }

  /// Hash code based on ID for use in Sets and Maps
  @override
  int get hashCode => id.hashCode;
  
  /// Check if receipt is blockchain certified
  /// 
  /// Returns true if the receipt has been successfully certified on the blockchain
  bool get isCertified => certificationStatus == 'confirmed';
  
  /// Check if certification is in progress
  bool get isCertifying => 
    certificationStatus == 'pending' || certificationStatus == 'submitted';
  
  /// Get blockchain explorer URL for this receipt's transaction
  String? get explorerUrl {
    if (blockchainTxHash == null) return null;
    return 'https://sepolia.etherscan.io/tx/$blockchainTxHash';
  }
}
